// Get URL display element from DOM
const urlDisplay = document.getElementById("url_holder")

/**
 * Updates value of url holder with url generated by createUrl
 */
 function updateUrlDisplay() {
  urlDisplay.value = createUrl();
}

/**
 * Generates a URL string containing all node data, to be used to restore 'sessions'
 * @returns {string} generated URL
 */
function createUrl() {
  let url = "placeholder/";
  updateNodeBuffer()

  let id = 0;
  nodeBuffer.forEach(pair => {
    // if on first pair, start with "?" rather than "&"
    if (id == 0) url += `?0_title=${pair[0]}&0_body=${pair[1]}`
    else url += `&${id}_title=${pair[0]}&${id}_body=${pair[1]}`
    id++
  })

  return url;
}